### ISSUE TITLE
Comportamiento incorrecto al iniciar sesión con Github

### ISSUE THREAD

**Issue by antsuabon** [decide-part-andarax-3/decide#130]
Se produce un comportamiento inadecuado cuando se intenta autenticase con Github en la aplicación.

El proceso que voy a describir a continuación lo he realizado con Google Chrome en la versión 87.0.4280.88 .

Los pasos a seguir son los siguientes:

1.- Clonamos la rama `develop`.
2.- Creamos un usuario administrador.
3.- Creamos una votación para realizar la prueba.
4.- Nos aseguramos que no existen ningún usuario asociado a la cuenta de Github que vamos a utilizar.
5.- Accedemos a la cabina de votación desde una nueva pestaña (sin cerrar la sesión de administrador).
6.- Nos autenticamos con Github.

Fallo encontrado: Cuando accedemos a la lista de usuarios desde el panel de administrador vemos que en lugar de haberse creado un usuario nuevo, se han asociado la cuenta de Github con la cuenta de administrador.

**Comment by PabloRodriguezGarrido11** [comment]
El error ocurre de la siguiente forma debido a que se crea una relación entre el nombre de usuario del superusuario registrado en el sistema en una de las tablas creadas por ```django-social-auth```, por lo que para resolver este conflicto:

1. Borramos el contenido de la tabla "social-auth".
2. Debemos de estar deslogueados antes de iniciar sesión mediante GitHub.
