### ISSUE TITLE
Documentación: Indicadores del proyecto

### ISSUE THREAD

**Issue by julsoutos** [decide-part-andarax-3/decide#135]
Realización del apartado "Indicadores del proyecto" del documento "Documento del proyecto (Decide Part Andarax Autenticación)" a entregar.

**Comment by julsoutos** [comment]
Se encuentra en proceso, ya que hasta el final del proyecto no se podrán cerrar los indicadores de la tabla, ya que se encuentran en constante actualización hasta el final del desarrollo.

**Comment by JulianGR** [comment]
Agregados mis "números" :+1:

**Comment by julsoutos** [comment]
Se han agregado los números de todos los miembros y se ha realizado la suma, finalizando así el apartado.
