### ISSUE TITLE
Error en las credenciales de GoogleOauth y Facebook

### ISSUE THREAD

**Issue by PabloRodriguezGarrido11** [decide-part-andarax-3/decide#176]
Al realizar los cambios en el settings necesarios para crear las variables de entorno de cada una de las aplicaciones de autenticación, Google, Github y Facebook, salta un error indicando que las credenciales no están permitidas.

1.- Despliegue de la aplicación en la rama de develop
2.- Introducimos las url http://localhost:8000/booth/x, siendo x una votación creada.
3.- Le damos a la opción de "login Google".
4.- Seleccionamos la cuenta de google con la que queremos iniciar sesión.

Tras realizar estos pasos se nos redirecciona a la siguiente página de error:
![unknown](https://user-images.githubusercontent.com/56022210/104233925-fa666c80-5452-11eb-852b-c5817f8ff377.png)

**Comment by antsuabon** [comment]
Este error se debía a que se habían realizado cambios en la aplicación de autenticación OAuth por Google y Facebook, pero aun no se habían efectuado los cambios en la aplicación.

Se ha solucionado corrigiendo la configuración de las credenciales para el despliegue local de la aplicación.

**Comment by PabloRodriguezGarrido11** [comment]
Efectivamente parece que era eso, ya funciona todo.
